macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

build_task:
  name: Gerar Executável macOS (Compatível 10.15)
  
  setup_script:
    # Usamos o python3 que já vem no macOS do Cirrus (geralmente 3.9 ou 3.10)
    - python3 -m pip install --upgrade pip
    - python3 -m pip install customtkinter openpyxl pyinstaller

  build_script:
    # Forçamos a compatibilidade retroativa
    - export MACOSX_DEPLOYMENT_TARGET=10.15
    - python3 -m PyInstaller --windowed --noconsole --onefile --collect-all customtkinter --icon=app.icns app.py

  binaries_artifacts:
    path: "dist/app"
