macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

build_task:
  name: Gerar Executável macOS (Compatível 10.15)
  
  # Usamos o python3 do sistema para evitar dependências modernas do Homebrew
  setup_script:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install customtkinter openpyxl pyinstaller

  build_script:
    - export MACOSX_DEPLOYMENT_TARGET=10.15
    # Voltamos ao --onefile para facilitar o envio de um único arquivo
    - python3 -m PyInstaller --windowed --noconsole --onefile --collect-all customtkinter --icon=app.icns app.py

  binaries_artifacts:
    path: "dist/app"
