name: Gerar Executável macOS (Compatibilidade Catalina)

on:
  push:
    branches: [ main ]  # O build inicia sempre que enviares código para a branch main

jobs:
  build:
    # Alterado para macos-12 para garantir que o GitHub encontre um servidor disponível
    runs-on: macos-12 

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        pip install customtkinter openpyxl pandas pyinstaller

    - name: Gerar Executável com PyInstaller
      env:
        # Força a compatibilidade com a versão 10.15 do teu utilizador
        MACOSX_DEPLOYMENT_TARGET: 10.15
      run: |
        # --windowed e --noconsole evitam que o terminal abra junto com a app
        # --onefile compacta tudo num único ficheiro
        # --collect-all garante que os ficheiros do customtkinter sejam incluídos
        pyinstaller --windowed --noconsole --onefile \
        --collect-all customtkinter \
        --icon=app.icns \
        app.py

    - name: Guardar Executável (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Sistema-Mac-Catalina
        path: dist/
