name: Gerar Executável macOS

on:
  push:
    branches: [ main ]  # Roda sempre que fizeres push para a branch main

jobs:
  build:
    runs-on: macos-latest  # Usa a versão mais recente do macOS na nuvem

    steps:
    - name: Checkout código
      uses: actions/checkout@v4  # Atualizado para v4

    - name: Configurar Python
      uses: actions/setup-python@v5  # Atualizado para v5
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        pip install customtkinter openpyxl pandas pyinstaller

    - name: Gerar Executável com PyInstaller
      run: |
        # O comando usa o teu app.py unificado
        pyinstaller --windowed --noconsole --onefile --collect-all customtkinter --icon=app.icns app.py

    - name: Guardar Executável (Artifact)
      uses: actions/upload-artifact@v4  # FIX: Atualizado para v4 para evitar o erro de depreciação
      with:
        name: Sistema-Mac-Final
        path: dist/app  # O executável gerado pelo PyInstaller
